apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: gp2-retain-sc
provisioner: kubernetes.io/aws-ebs
parameters:
type: gp2
encrypted: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
