apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSetting
metadata:
  name: cis-compliance
  namespace: openshift-compliance
rawResultStorage:
  storageClassName: gp2
  pvAccessModes:
  - ReadWriteOnce
  rotation: 3
  size: 5Gi
roles:
- worker
- master
- infra
scanTolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  operator: Exists
- effect: NoSchedule
  key: "infra"
  value: "true"
  operator: "Equal"
schedule: "*/5 * * * *"
