apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: cluster-operator-admin
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - operatorhubs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - catalogsources
  - installplans
  - subscriptions
  - operatorgroups
  verbs:
  - "*"
- apiGroups:
  - packages.operators.coreos.com
  resources:
  - packagemanifests
  - packagemanifests/icon
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - project.openshift.io
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
