apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: infra-machine-health-check
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: infra
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/cluster-api-machineset: cluster-pkht6-vvs4z-infra-ap-southeast-1a
  unhealthyConditions:
  - type:    "Ready"
    timeout: "180s" 
    status: "False"
  - type:    "Ready"
    timeout: "90s" 
    status: "Unknown"
  maxUnhealthy: "70%" 
  nodeStartupTimeout: "10m" 
